controller_list:
  - name: fake_snake_robot2_controller
    type: $(arg execution_type)
    joints:
      - base2_joint
      - rail2_1_joint1
      - rail2_1_joint2
      - rail2_1_joint3
      - rail2_1_joint4
      - rail2_1_joint5
      - rail2_2_joint1
      - rail2_2_joint2
      - rail2_2_joint3
      - rail2_2_joint4
      - rail2_2_joint5
      - rail2_3_joint1
      - rail2_3_joint2
      - rail2_3_joint3
      - rail2_3_joint4
      - rail2_3_joint5
      - rail2_4_joint1
      - rail2_4_joint2
      - rail2_4_joint3
      - rail2_4_joint4
      - rail2_4_joint5
      - rail2_5_joint1
      - rail2_5_joint2
      - rail2_5_joint3
      - rail2_5_joint4
      - rail2_5_joint5
      - rail2_6_joint1
      - rail2_6_joint2
      - rail2_6_joint3
      - rail2_6_joint4
      - rail2_6_joint5
      - rail2_7_joint1
      - rail2_7_joint2
      - rail2_7_joint3
      - rail2_7_joint4
      - rail2_7_joint5
      - rail2_8_joint1
      - rail2_8_joint2
      - rail2_8_joint3
      - rail2_8_joint4
      - rail2_8_joint5
      - rail2_9_joint1
      - rail2_9_joint2
      - rail2_9_joint3
      - rail2_9_joint4
      - rail2_9_joint5
      - rail2_10_joint1
      - rail2_10_joint2
      - rail2_10_joint3
      - rail2_10_joint4
      - rail2_10_joint5
      - rail2_11_joint1
      - rail2_11_joint2
      - rail2_11_joint3
      - rail2_11_joint4
      - rail2_11_joint5
      - rail2_12_joint1
      - rail2_12_joint2
      - rail2_12_joint3
      - rail2_12_joint4
      - rail2_12_joint5
initial:  # Define initial robot poses.
#  - group: snake_robot2
#    pose: home

  []