# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rail2_1_joint1
    - rail2_1_joint2
    - rail2_1_joint3
    - rail2_1_joint4
    - rail2_1_joint5
    - rail2_2_joint1
    - rail2_2_joint2
    - rail2_2_joint3
    - rail2_2_joint4
    - rail2_2_joint5
    - rail2_3_joint1
    - rail2_3_joint2
    - rail2_3_joint3
    - rail2_3_joint4
    - rail2_3_joint5
    - rail2_4_joint1
    - rail2_4_joint2
    - rail2_4_joint3
    - rail2_4_joint4
    - rail2_4_joint5
    - rail2_5_joint1
    - rail2_5_joint2
    - rail2_5_joint3
    - rail2_5_joint4
    - rail2_5_joint5
    - rail2_6_joint1
    - rail2_6_joint2
    - rail2_6_joint3
    - rail2_6_joint4
    - rail2_6_joint5
    - rail2_7_joint1
    - rail2_7_joint2
    - rail2_7_joint3
    - rail2_7_joint4
    - rail2_7_joint5
    - rail2_8_joint1
    - rail2_8_joint2
    - rail2_8_joint3
    - rail2_8_joint4
    - rail2_8_joint5
    - rail2_9_joint1
    - rail2_9_joint2
    - rail2_9_joint3
    - rail2_9_joint4
    - rail2_9_joint5
    - rail2_10_joint1
    - rail2_10_joint2
    - rail2_10_joint3
    - rail2_10_joint4
    - rail2_10_joint5
    - rail2_11_joint1
    - rail2_11_joint2
    - rail2_11_joint3
    - rail2_11_joint4
    - rail2_11_joint5
    - rail2_12_joint1
    - rail2_12_joint2
    - rail2_12_joint3
    - rail2_12_joint4
    - rail2_12_joint5
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: snake_robot2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rail2_1_joint1
      - rail2_1_joint2
      - rail2_1_joint3
      - rail2_1_joint4
      - rail2_1_joint5
      - rail2_2_joint1
      - rail2_2_joint2
      - rail2_2_joint3
      - rail2_2_joint4
      - rail2_2_joint5
      - rail2_3_joint1
      - rail2_3_joint2
      - rail2_3_joint3
      - rail2_3_joint4
      - rail2_3_joint5
      - rail2_4_joint1
      - rail2_4_joint2
      - rail2_4_joint3
      - rail2_4_joint4
      - rail2_4_joint5
      - rail2_5_joint1
      - rail2_5_joint2
      - rail2_5_joint3
      - rail2_5_joint4
      - rail2_5_joint5
      - rail2_6_joint1
      - rail2_6_joint2
      - rail2_6_joint3
      - rail2_6_joint4
      - rail2_6_joint5
      - rail2_7_joint1
      - rail2_7_joint2
      - rail2_7_joint3
      - rail2_7_joint4
      - rail2_7_joint5
      - rail2_8_joint1
      - rail2_8_joint2
      - rail2_8_joint3
      - rail2_8_joint4
      - rail2_8_joint5
      - rail2_9_joint1
      - rail2_9_joint2
      - rail2_9_joint3
      - rail2_9_joint4
      - rail2_9_joint5
      - rail2_10_joint1
      - rail2_10_joint2
      - rail2_10_joint3
      - rail2_10_joint4
      - rail2_10_joint5
      - rail2_11_joint1
      - rail2_11_joint2
      - rail2_11_joint3
      - rail2_11_joint4
      - rail2_11_joint5
      - rail2_12_joint1
      - rail2_12_joint2
      - rail2_12_joint3
      - rail2_12_joint4
      - rail2_12_joint5